apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: '${CLUSTER_NAME}'
  name: '${CLUSTER_NAME}'
  namespace: '${NAMESPACE}'
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  topology:
    version: v1.29.0
    class: capv-quick-start
    controlPlane:
      replicas: 1
    workers:
      machineDeployments:
      - class: node-pool
        name: md-0
        replicas: 0
